name: true_false
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - src/img/
  fonts:
    - family: 'Comfortaa'
      fonts:
        - asset: src/fonts/Comfortaa-VariableFont_wght.ttf
    - family: 'Raleway'
      fonts:
        - asset: src/fonts/Raleway-VariableFont_wght.ttf